spring:
  application:
    name: sb-ecom

server:
  port: 8081
logging:
    level:
        org:
            springframework: 
                security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
    pattern:
        console: "%green(%d{HH:mm:ss.SSS}) %blue([%-5level]) %red([%thread]) %yellow(%logger{15}) - %msg%n"
